package get

const (
	Tag1                = "业务线（1）(必填)"
	TagX                = "独立业务（X)(必填)"
	Tag2                = "项目名称（必填）"
	ResourceID          = "资源ID"
	ResourceName        = "资源名称"
	ResourceCategory    = "资源大类"
	ResourceSubCategory = "资源小类"
	Specification       = "规格"
	CPU                 = "CPU/vCPU(核)"
	Memory              = "内存(GB)"
	InternalBandwidth   = "内网带宽（Gbps)"
	Image               = "镜像"
	CloudPool           = "归属云池"
	Node                = "节点"
	AvailabilityZone    = "可用区"
	SystemDiskSize      = "系统盘容量（GB）"
	SystemDiskSpec      = "系统盘规格"
	BillingMethod       = "计费方式"

	NICName               = "网卡名称"
	NICMAC                = "网卡MAC"
	NICVPC                = "VPC"
	NICSubnet             = "子网"
	NICIPv4PrivateAddress = "IPV4内网地址"
	NICIPv4PrivateMask    = "IPV4内网地址掩码"
	NICIPv6Address        = "IPV6地址"
	NICIPv6Mask           = "IPV6地址掩码"
	NICSecurityGroup      = "安全组"

	VPC           = "VPC"
	LowerVPC      = "vpc"
	Subnet        = "子网"
	SecurityGroup = "安全组"

	Capacity  = "容量（GB）"
	IsShare   = "共享状态"
	Mount     = "挂载"
	Bandwidth = "带宽"

	totalFlow              = "总流量"
	Type                   = "类型"
	IPv4PrivateAddress     = "IPv4内网地址"
	IPv4PublicAddress      = "IPv4公网地址"
	PublicIPv4Address      = "公网IPv4地址"
	IPv6Address            = "IPv6地址"
	TrafficPacketDeduction = "流量包抵扣"
	BindingResourceType    = "绑定资源类型"
	BindingResourceName    = "绑定资源名称"
	BindingResourceID      = "绑定资源ID"
	DeductedIP             = "纳入抵扣IP"
	RelatedResources       = "关联资源"

	IPType                   = "IP类型"
	UserSubnet               = "用户子网"
	AccessNodeRegion         = "接入节点地域"
	AccessNodeAddress        = "接入节点详细地址"
	AccessNodeContact        = "接入节点联系人"
	AccessNodeAccountManager = "接入节点客户经理"
	AccountManager           = "客户经理"

	NodeIP                   = "节点ip"
	EndpointNodeServiceName  = "终端节点服务名称"
	NetworkProductInstanceID = "网络产品实例ID"

	VGWAndAggDockingIPMaster          = "vgw与汇聚设备对接IP(主）"
	VGWAndAggDockingIPBackup          = "vgw与汇聚设备对接IP(备）"
	AggAndVGWDockingIPMaster          = "汇聚设备与vgw对接IP(主）"
	AggAndVGWDockingIPBackup          = "汇聚设备与vgw对接IP(备）"
	AggAndVGWDockingVLANMaster        = "汇聚设备与vgw对接VLAN（主）"
	AggAndVGWDockingVLANBackup        = "汇聚设备与vgw对接VLAN（备）"
	AggAndCustomerDockingLogicalPort  = "汇聚设备与客户设备对接逻辑端口"
	AggAndCustomerDockingPhysicalPort = "汇聚设备与客户设备对接物理端口"
	Device1                           = "设备1位置"
	Device2                           = "设备2位置"
	ResourcePool                      = "资源池"

	RelatedComputeResources = "关联的计算资源"

	Architecture = "架构"
	ImageVersion = "镜像版本"
	PrivateIPv4  = "内网IPV4"
	PrivateIPv6  = "内网IPV6"
	PublicIPv4   = "公网IPV4"
	PortInfo     = "端口信息"
)
